set feedback on
set echo on

drop user hotsos cascade;

CREATE USER HOTSOS
  IDENTIFIED BY HOTSOS
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

  GRANT RESOURCE TO HOTSOS;
  GRANT CONNECT TO HOTSOS;
  ALTER USER HOTSOS DEFAULT ROLE ALL;

  GRANT CREATE TYPE TO HOTSOS;
  GRANT CREATE PROCEDURE TO HOTSOS;
  GRANT CREATE TRIGGER TO HOTSOS;
  GRANT CREATE TABLE TO HOTSOS;
  GRANT CREATE SESSION TO HOTSOS;
  GRANT CREATE PUBLIC SYNONYM TO HOTSOS;
  GRANT CREATE SEQUENCE TO HOTSOS;
  GRANT CREATE SYNONYM TO HOTSOS;
  GRANT ALTER SESSION TO HOTSOS;

  ALTER USER HOTSOS QUOTA UNLIMITED ON USERS;

set echo off
set feedback off

