explain plan for
UPDATE T_KSS25469_BREAK_SCHED2 SET SEGMENT_END = :B5 , AMOUNT = AMOUNT + :B4 WHERE SHIFTASSIGNID = :B3 AND ORGIDSID = :B2 AND SEGMENT_SORT_ORDER = :B1 AND SHIFTSEGMENTTYPE NOT IN 'Break'
;
select * from table(dbms_xplan.display);
