SELECT	
count(*)
FROM	KTC_PAYROLL_EMPLOYEES KPE
JOIN WTKEMPLOYEE WE ON KPE.PERSONID = WE.WTKEMPLOYEEID
JOIN PERSON P ON 1=1
AND WE.EMPLOYEEID = P.PERSONID
AND P.MGRSIGNOFFTHRUDTM >= (TRUNC(SYSDATE, 'DAY')-1)
AND P.PERSONID > 0
--Total records info paycode relationships
JOIN WFCTOTAL T ON 1=1
AND WE.EMPLOYEEID = T.EMPLOYEEID
AND T.APPLYDTM >= KPE.START_DATE
AND T.APPLYDTM < KPE.END_DATE
JOIN PAYCODE PC ON 1=1
AND	T.PAYCODEID = PC.PAYCODEID
AND PC.TYPE = 'P'
AND PC.NAME LIKE 'Pay %'
--Person Home Worked labor account info
JOIN COMBHOMEACCT CA ON 1=1
AND P.PERSONID = CA.EMPLOYEEID
AND CA.EFFECTIVEDTM <= T.APPLYDTM
AND CA.EXPIRATIONDTM > T.APPLYDTM
JOIN LABORACCT HA ON CA.LABORACCTID = HA.LABORACCTID
JOIN LABORACCT LA ON T.LABORACCTID = LA.LABORACCTID
--Person Status Information
JOIN PERSONSTATUSMM PS ON 1=1
AND	P.PERSONID = PS.PERSONID
AND PS.EMPLOYMENTSTATID <> 0
AND PS.EFFECTIVEDTM <= T.ADJAPPLYDTM
AND PS.EXPIRATIONDTM > T.ADJAPPLYDTM
--Custome fields Worker Type
LEFT OUTER JOIN PERSONCSTMDATA PC1 ON 1=1
AND P.PERSONID = PC1.PERSONID
AND PC1.CUSTOMDATADEFID = 1
LEFT OUTER JOIN PERSONCSTMDATA PC2 ON 1=1
AND	P.PERSONID = PC2.PERSONID
AND PC2.CUSTOMDATADEFID = 2
LEFT OUTER JOIN KTC_CUSTOM_STAGING KCS ON	P.PERSONID = KCS.EMP_ID	
LEFT OUTER JOIN WORKERTYPE WT ON WE.WORKERTYPEID = WT.WORKERTYPEID
--Used to check "historical date" for match on week of A/B cycles (pulls weeknum and start and end dates for matching period)
LEFT OUTER JOIN KTC_PAYPERIODS PCA ON 1=1
AND KPE.PAYCYCLE = 'A'
AND T.ADJAPPLYDTM >= PCA.A_WK1START
AND T.ADJAPPLYDTM <= PCA.A_WK2END
--
LEFT OUTER JOIN KTC_PAYPERIODS PCB ON 1=1
AND KPE.PAYCYCLE = 'B'
AND T.ADJAPPLYDTM >= PCB.B_WK1START
AND T.ADJAPPLYDTM <= PCB.B_WK2END
--
LEFT OUTER JOIN KTC_PAYPERIODS PPSE ON 1=1
AND T.APPLYDTM >= PPSE.B_WK1START
AND T.APPLYDTM <= PPSE.B_WK2END
--Voucher DQ's
LEFT OUTER JOIN VOUCHERTMSHTITEMS VI ON T.WFCTOTALID = VI.WFCTOTALID
LEFT OUTER JOIN VOUCHERADJPAYCODE VPC ON PC.NAME = VPC.NAME
WHERE	1=1
AND (T.DURATIONSECSQTY <> 0 OR T.MONEYAMT <> 0)
AND KPE.PAYCYCLE IN ('A', 'B')
AND VI.WFCTOTALID IS NULL
AND VPC.NAME IS NULL
;
