rcld19-scan.target.com:1522/PCLS01 as sysdba
rcld19-scan.target.com:1522/PCLD01 as sysdba


CREATE TABLE "PCLMGR"."CLOSEDLOOPCARD_NEW"
   (  "CLOSEDLOOPCARD_ID" RAW(255) NOT NULL ENABLE,
  "PRODUCT_TYPE" NUMBER(10,0) NOT NULL ENABLE,
  "PRODUCT_BARCODE" VARCHAR2(50) NOT NULL ENABLE,
  "TRANSACTION_TYPE" VARCHAR2(20) NOT NULL ENABLE,
  "CLIENT_SYSTEM_NAME" VARCHAR2(20) NOT NULL ENABLE,
  "CLIENT_VERSION" VARCHAR2(20) NOT NULL ENABLE,
  "COMPANY_CODE" NUMBER(10,0) NOT NULL ENABLE,
  "STORE_NUMBER" NUMBER(10,0) NOT NULL ENABLE,
  "TERMINAL_ID" NUMBER(10,0) NOT NULL ENABLE,
  "TRANSACTION_SEQUENCE_NUMBER" NUMBER(10,0) NOT NULL ENABLE,
  "TRANSACTION_LINE_NUMBER" NUMBER(10,0) NOT NULL ENABLE,
  "TRANSMISSION_DATE_TIME" TIMESTAMP (6),
  "TRANSACTION_DATE_LOCAL" VARCHAR2(6) NOT NULL ENABLE,
  "TRANSACTION_TIME_LOCAL" VARCHAR2(6) NOT NULL ENABLE,
  "CLIENT_ENTRY_MODE" VARCHAR2(3) NOT NULL ENABLE,
  "PREPAIDCARD_AMOUNT" NUMBER(10,0),
  "PREPAIDCARD_BALANCE" VARCHAR2(13),
  "AUTHORIZER_RESPONSE_CODE" VARCHAR2(20),
  "SERVICE_RESPONSE_CODE" VARCHAR2(3),
  "TRANSACTION_UNIQUE_ID" VARCHAR2(30),
  "COR_TRANSACTION_UNIQUE_ID" VARCHAR2(30),
  "CREATE_DATE_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
  "SIMULATOR_OVERRIDE" VARCHAR2(5),
  "SIMULATOR_RESPONSE_CODE" NUMBER(10,0),
  "PREPAIDCARD_STATUS" VARCHAR2(20),
   CONSTRAINT "CLOSEDLOOPCARD_PK_NEW" PRIMARY KEY ("CLOSEDLOOPCARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PCLDAT01"  ENABLE
   ) 
   SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PCLDAT01"
     PARTITION BY RANGE (CREATE_DATE_TIME)
   INTERVAL(NUMTOYMINTERVAL(1, 'MONTH')) 
    (
       PARTITION pos_data_DEC16 VALUES LESS THAN (TO_DATE('01-01-2017', 'MM-DD-YYYY')),
       PARTITION pos_data_JAN17 VALUES LESS THAN (TO_DATE('02-01-2017', 'MM-DD-YYYY')),
       PARTITION pos_data_FEB17 VALUES LESS THAN (TO_DATE('03-01-2017', 'MM-DD-YYYY')),
       PARTITION pos_data_MAR17 VALUES LESS THAN (TO_DATE('04-01-2017', 'MM-DD-YYYY')),
       PARTITION pos_data_APR17 VALUES LESS THAN (TO_DATE('05-01-2017', 'MM-DD-YYYY')),
       PARTITION pos_data_MAY17 VALUES LESS THAN (TO_DATE('06-01-2017', 'MM-DD-YYYY')),
       PARTITION pos_data_JUN17 VALUES LESS THAN (TO_DATE('07-01-2017', 'MM-DD-YYYY')),
       PARTITION pos_data_JUL17 VALUES LESS THAN (TO_DATE('08-01-2017', 'MM-DD-YYYY')),
       PARTITION pos_data_AUG17 VALUES LESS THAN (TO_DATE('09-01-2017', 'MM-DD-YYYY')),
       PARTITION pos_data_SEP17 VALUES LESS THAN (TO_DATE('10-01-2017', 'MM-DD-YYYY')),
       PARTITION pos_data_OCT17 VALUES LESS THAN (TO_DATE('11-01-2017', 'MM-DD-YYYY')),
       PARTITION pos_data_NOV17 VALUES LESS THAN (TO_DATE('12-01-2017', 'MM-DD-YYYY')),
       PARTITION pos_data_DEC17 VALUES LESS THAN (TO_DATE('01-01-2018', 'MM-DD-YYYY')),
       PARTITION pos_data_JAN18 VALUES LESS THAN (TO_DATE('02-01-2018', 'MM-DD-YYYY')),
       PARTITION pos_data_FEB18 VALUES LESS THAN (TO_DATE('03-01-2018', 'MM-DD-YYYY')),
       PARTITION pos_data_MAR18 VALUES LESS THAN (TO_DATE('04-01-2018', 'MM-DD-YYYY')),
       PARTITION pos_data_APR18 VALUES LESS THAN (TO_DATE('05-01-2018', 'MM-DD-YYYY')),
       PARTITION pos_data_MAY18 VALUES LESS THAN (TO_DATE('06-01-2018', 'MM-DD-YYYY')),
       PARTITION pos_data_JUN18 VALUES LESS THAN (TO_DATE('07-01-2018', 'MM-DD-YYYY')),
       PARTITION pos_data_JUL18 VALUES LESS THAN (TO_DATE('08-01-2018', 'MM-DD-YYYY')),
       PARTITION pos_data_AUG18 VALUES LESS THAN (TO_DATE('09-01-2018', 'MM-DD-YYYY')),
       PARTITION pos_data_SEP18 VALUES LESS THAN (TO_DATE('10-01-2018', 'MM-DD-YYYY')),
       PARTITION pos_data_OCT18 VALUES LESS THAN (TO_DATE('11-01-2018', 'MM-DD-YYYY')),
       PARTITION pos_data_NOV18 VALUES LESS THAN (TO_DATE('12-01-2018', 'MM-DD-YYYY')),
       PARTITION pos_data_DEC18 VALUES LESS THAN (TO_DATE('01-01-2019', 'MM-DD-YYYY')),
       PARTITION pos_data_JAN19 VALUES LESS THAN (TO_DATE('02-01-2019', 'MM-DD-YYYY')),
       PARTITION pos_data_FEB19 VALUES LESS THAN (TO_DATE('03-01-2019', 'MM-DD-YYYY')),
       PARTITION pos_data_MAR19 VALUES LESS THAN (TO_DATE('04-01-2019', 'MM-DD-YYYY')),
       PARTITION pos_data_APR19 VALUES LESS THAN (TO_DATE('05-01-2019', 'MM-DD-YYYY')),
       PARTITION pos_data_MAY19 VALUES LESS THAN (TO_DATE('06-01-2019', 'MM-DD-YYYY')),
       PARTITION pos_data_JUN19 VALUES LESS THAN (TO_DATE('07-01-2019', 'MM-DD-YYYY')),
       PARTITION pos_data_JUL19 VALUES LESS THAN (TO_DATE('08-01-2019', 'MM-DD-YYYY')),
       PARTITION pos_data_AUG19 VALUES LESS THAN (TO_DATE('09-01-2019', 'MM-DD-YYYY')),
       PARTITION pos_data_SEP19 VALUES LESS THAN (TO_DATE('10-01-2019', 'MM-DD-YYYY')),
       PARTITION pos_data_OCT19 VALUES LESS THAN (TO_DATE('11-01-2019', 'MM-DD-YYYY')),
       PARTITION pos_data_NOV19 VALUES LESS THAN (TO_DATE('12-01-2019', 'MM-DD-YYYY')),
       PARTITION pos_data_DEC19 VALUES LESS THAN (TO_DATE('01-01-2020', 'MM-DD-YYYY')),
       PARTITION pos_data_JAN20 VALUES LESS THAN (TO_DATE('02-01-2020', 'MM-DD-YYYY')),
       PARTITION pos_data_FEB20 VALUES LESS THAN (TO_DATE('03-01-2020', 'MM-DD-YYYY')),
       PARTITION pos_data_MAR20 VALUES LESS THAN (TO_DATE('04-01-2020', 'MM-DD-YYYY')),
       PARTITION pos_data_APR20 VALUES LESS THAN (TO_DATE('05-01-2020', 'MM-DD-YYYY')),
       PARTITION pos_data_MAY20 VALUES LESS THAN (TO_DATE('06-01-2020', 'MM-DD-YYYY')),
       PARTITION pos_data_JUN20 VALUES LESS THAN (TO_DATE('07-01-2020', 'MM-DD-YYYY')),
       PARTITION pos_data_JUL20 VALUES LESS THAN (TO_DATE('08-01-2020', 'MM-DD-YYYY')),
       PARTITION pos_data_AUG20 VALUES LESS THAN (TO_DATE('09-01-2020', 'MM-DD-YYYY')),
       PARTITION pos_data_SEP20 VALUES LESS THAN (TO_DATE('10-01-2020', 'MM-DD-YYYY')),
       PARTITION pos_data_OCT20 VALUES LESS THAN (TO_DATE('11-01-2020', 'MM-DD-YYYY')),
       PARTITION pos_data_NOV20 VALUES LESS THAN (TO_DATE('12-01-2020', 'MM-DD-YYYY')),
       PARTITION pos_data_DEC20 VALUES LESS THAN (TO_DATE('01-01-2021', 'MM-DD-YYYY'))
    )
/


insert into "PCLMGR"."CLOSEDLOOPCARD_NEW" 
  (    CLOSEDLOOPCARD_ID, PRODUCT_TYPE, PRODUCT_BARCODE, TRANSACTION_TYPE, 
      CLIENT_SYSTEM_NAME, CLIENT_VERSION, COMPANY_CODE,
       STORE_NUMBER, TERMINAL_ID, TRANSACTION_SEQUENCE_NUMBER, TRANSACTION_LINE_NUMBER,
       TRANSMISSION_DATE_TIME, TRANSACTION_DATE_LOCAL, TRANSACTION_TIME_LOCAL, CLIENT_ENTRY_MODE, CREATE_DATE_TIME
  )
  (  select
       CLOSEDLOOPCARD_ID, PRODUCT_TYPE, PRODUCT_BARCODE, TRANSACTION_TYPE, 
       CLIENT_SYSTEM_NAME, CLIENT_VERSION, COMPANY_CODE,
       STORE_NUMBER, TERMINAL_ID, TRANSACTION_SEQUENCE_NUMBER, TRANSACTION_LINE_NUMBER,
       TRANSMISSION_DATE_TIME, TRANSACTION_DATE_LOCAL, TRANSACTION_TIME_LOCAL, CLIENT_ENTRY_MODE, TRANSMISSION_DATE_TIME as "CREATE_DATE_TIME"
       from "PCLMGR"."CLOSEDLOOPCARD"
  )
/

CREATE INDEX "PCLMGR"."PRODUCT_BARCODE_IDX1" ON "PCLMGR"."CLOSEDLOOPCARD_NEW" ("PRODUCT_BARCODE") INITRANS 200 TABLESPACE "PCLDAT01";
alter table "PCLMGR"."CLOSEDLOOPCARD" rename to CLOSEDLOOPCARD_OLD;
alter table "PCLMGR"."CLOSEDLOOPCARD_NEW" rename to CLOSEDLOOPCARD;

